export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_TITLE = "SET_TITLE";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const SENDCODE_SUCCESS = "SENDCODE_SUCCESS";
export const SENDCODE_FAIL = "SENDCODE_FAIL";

export const VALIDATE_CODE_SUCCESS = "VALIDATE_CODE_SUCCESS";
export const VALIDATE_CODE_FAIL = "VALIDATE_CODE_FAIL";

export const SET_SALES_LIST = "SET_SALES_LIST";
export const SET_TT_DON_VI = "SET_TT_DON_VI";
export const SET_NGANH_HANG_LIST = "SET_NGANH_HANG_LIST";
export const SET_CURRENT_DON_VI = "SET_CURRENT_DON_VI";
export const SET_LOAI_DANHMUC_THUCHI = "SET_LOAI_DANHMUC_THUCHI";
export const SET_TINHTRANG_DONHANG = "SET_TINHTRANG_DONHANG";

export const RE_FETCH_DATA = "RE_FETCH_DATA";
export const LOAD_DATA_ORDERED = "LOAD_DATA_ORDERED";
export const SET_LIST_TABLE = "SET_LIST_TABLE";
export const UPDATE_LIST_TABLE = "UPDATE_LIST_TABLE";
export const ADD_NEW_TABLE = "ADD_NEW_TABLE";
export const REMOTE_TABLE = "REMOTE_TABLE";
export const SET_TABLE_CURRENT = "SET_TABLE_CURRENT";

export const SET_THUC_DON = "SET_THUC_DON";
export const SET_TOTAL_AMOUNT = "SET_TOTAL_AMOUNT";
export const SET_LIST_THUC_DON = "SET_LIST_THUC_DON"

export const SET_OUTLET = "SET_OUTLET";
export const SET_LIST_OUTLET = "SET_LIST_OUTLET";

export const SET_ORDER_NEWLIST = "SET_ORDER_NEWLIST"
export const SET_ORDERED_LIST = "SET_ORDERED_LIST"
export const ADD_MENU_TO_ORDER = "ADD_MENU_TO_ORDER"
export const UPDATE_MENU_ORDER = "UPDATE_MENU_ORDER"
export const REMOVE_MENU_ORDER = "REMOVE_MENU_ORDER"
export const SET_CHIETKHAU_BILL = "SET_CHIETKHAU_BILL";
export const SET_LOAI_DON_HANG = "SET_LOAI_DON_HANG";

export const SET_DANH_SACH_MATHANG = "SET_DANH_SACH_MATHANG";
export const UPDATE_IS_CHECK_MATHANG = "UPDATE_IS_CHECK_MATHANG";

export const SHOW_FOOTER = 'SHOW_FOOTER';

export const SET_SELECTED_CUSTOMER = 'SET_SELECTED_CUSTOMER'
export const SET_DANH_SACH_KHACHHANG = "SET_DANH_SACH_KHACHHANG"
export const UPDATE_IS_CHECK_KHACHHANG = "UPDATE_IS_CHECK_KHACHHANG";

export const SET_DANH_SACH_KHUYENMAI_AD = "SET_DANH_SACH_KHUYENMAI_AD";
export const UPDATE_IS_CHECK_KHUYENMAI_AD = "UPDATE_IS_CHECK_KHUYENMAI_AD";

export const SET_DANH_SACH_THE_THANHVIEN = "SET_DANH_SACH_THE_THANHVIEN";
export const UPDATE_IS_CHECK_THE_THANHVIEN = "UPDATE_IS_CHECK_THE_THANHVIEN";
export const SET_DANH_SACH_NHOM_KH = "SET_DANH_SACH_NHOM_KH";
export const UPDATE_IS_CHECK_NHOM_KH = "UPDATE_IS_CHECK_NHOM_KH";

export const SET_LIST_HTTT = 'SET_LIST_HTTT';
export const SET_FILTER_DATA = 'SET_FILTER_DATA';
export const SET_ID_BILL_DELETE = 'SET_ID_BILL_DELETE';
export const SET_LIST_BILL = 'SET_LIST_BILL';
export const SET_KHUYEN_MAI = 'SET_KHUYEN_MAI';
export const SET_DANH_SACH_DANHMUC = "SET_DANH_SACH_DANHMUC";
export const UPDATE_IS_CHECK_DANHMUC = "UPDATE_IS_CHECK_DANHMUC";